[tools]
pnpm = "10.12.1"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.deploy]
run = "tsx alchemy.run.ts"

[tasks.tear-down]
run = "tsx alchemy.run.ts --destroy"

[tasks.dev]
run = "astro dev"

[tasks.build]
run = "astro build"

[tasks.clean]
run = ["rm -rf .astro", "rm -rf dist", "rm -rf .wrangler"]

[tasks.preview]
run = "wrangler dev ./dist/_worker.js"
depends = ["build"]

[tasks."last-deployment"]
run = "wrangler pages deployment list"

[tasks.test]
run = "vitest"

[tasks."test:ui"]
run = "vitest --ui"

[tasks."test:coverage"]
run = "vitest --coverage"

[tasks."open:deployment"]
run = "open https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}/workers/services/view/abstract-industries/production/metrics"
