[tools]
node = "22.15.0"
pnpm = "10.12.1"

[hooks]
postinstall = "pnpm install"

[settings]
experimental = true # Enabled to allow hooks

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.deploy]
run = "tsx alchemy.run.ts"

[tasks.tear-down]
run = "tsx alchemy.run.ts --destroy"

[tasks.dev]
run = "astro dev"

[tasks.build]
run = "astro build"

[tasks.clean]
run = ["rm -rf .astro", "rm -rf dist", "rm -rf .wrangler"]

[tasks.fmt]
run = "biome check --write --unsafe ."

[tasks.verify]
depends = ["typecheck", "lint", "test run"]

[tasks.typecheck]
run = "tsc --noEmit"

[tasks.lint]
run = "biome check ."

[tasks.preview]
run = "wrangler dev ./dist/_worker.js"
depends = ["build"]

[tasks."last-deployment"]
run = "wrangler pages deployment list"

[tasks.test]
run = "vitest"

[tasks."test:ui"]
run = "vitest --ui"

[tasks."test:coverage"]
run = "vitest --coverage"

[tasks."open:deployment"]
run = "open https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}/workers/services/view/abstract-industries/production/metrics"

[tasks.logs]
run = "wrangler tail abstract-industries"
