[tools]
pnpm = "10.12.1"

[env]
_.path = "node_modules/.bin"
_.file = ".env"

[tasks.deploy]
run = "tsx alchemy.run.ts"

[tasks.tear-down]
run = "tsx alchemy.run.ts --destroy"

[tasks.dev]
run = "astro dev"

[tasks.build]
run = "astro build"

[tasks.preview]
run = "astro preview"

[tasks.test]
run = "vitest"

[tasks."test:ui"]
run = "vitest --ui"

[tasks."test:coverage"]
run = "vitest --coverage"
